#!/bin/sh

# taken from git's GIT-VERSION-FILE

DEF_VER=$1
UVF=version.h
LF='
'

if test -d ../.git -o -f ../.git &&
    VN=$(git describe HEAD 2>/dev/null) &&
    case "$VN" in
	*$LF*) (exit 1) ;;
	v[0-9]*)
	    git update-index -q --refresh
	    test -z "$(git diff-index --name-only HEAD --)" ||
	    VN="$VN-dirty" ;;
    esac
then
    VN=$(echo "$VN" | sed -e 's/-/./g');
else
    VN="$DEF_VER"
fi

VN=$(expr "$VN" : v*'\(.*\)')
echo $VN
echo "#define UKB_UKB_VERSION \"$VN\"" >$UVF
